UPDATE locations SET location_code = '101', address = '920 W. State Highway 46', city = 'Spencer', state = 'IN', zip_code = '47460' WHERE name LIKE '%- 101' OR name LIKE '%- 101';
UPDATE locations SET location_code = '103', address = '1143 23rd Street', city = 'Tell City', state = 'IN', zip_code = '47586' WHERE name LIKE '%- 103' OR name LIKE '%- 103';
UPDATE locations SET location_code = '104', address = '2494 N. Lebanon Street', city = 'Lebanon', state = 'IN', zip_code = '46052' WHERE name LIKE '%- 104' OR name LIKE '%- 104';
UPDATE locations SET location_code = '105', address = '2911 Green Valley Road', city = 'New Albany AW', state = 'IN', zip_code = '47150' WHERE name LIKE '%- 105' OR name LIKE '%- 105';
UPDATE locations SET location_code = '106', address = '800 St. Joseph Drive', city = 'Kokomo WP', state = 'IN', zip_code = '46901' WHERE name LIKE '%- 106' OR name LIKE '%- 106';
UPDATE locations SET location_code = '107', address = '2011 Chapa Drive', city = 'Columbus', state = 'IN', zip_code = '47203' WHERE name LIKE '%- 107' OR name LIKE '%- 107';
UPDATE locations SET location_code = '108', address = '3150 St. Charles Street', city = 'Jasper', state = 'IN', zip_code = '47546' WHERE name LIKE '%- 108' OR name LIKE '%- 108';
UPDATE locations SET location_code = '109', address = '1675 W. Tipton Street', city = 'Seymour', state = 'IN', zip_code = '47274' WHERE name LIKE '%- 109' OR name LIKE '%- 109';
UPDATE locations SET location_code = '110', address = '1325 Rockport Road', city = 'Boonville', state = 'IN', zip_code = '47601' WHERE name LIKE '%- 110' OR name LIKE '%- 110';
UPDATE locations SET location_code = '111', address = '3001 Galaxy Drive', city = 'Evansville RP', state = 'IN', zip_code = '47715' WHERE name LIKE '%- 111' OR name LIKE '%- 111';
UPDATE locations SET location_code = '112', address = '1707 Bethany Road', city = 'Anderson', state = 'IN', zip_code = '46012' WHERE name LIKE '%- 112' OR name LIKE '%- 112';
UPDATE locations SET location_code = '114', address = '1217 US Highway 62E', city = 'Cynthiana', state = 'KY', zip_code = '41031' WHERE name LIKE '%- 114' OR name LIKE '%- 114';
UPDATE locations SET location_code = '115', address = '3100 Shawnee Drive S.', city = 'Bedford', state = 'IN', zip_code = '47421' WHERE name LIKE '%- 115' OR name LIKE '%- 115';
UPDATE locations SET location_code = '116', address = '188 Thornton Road', city = 'Hanover', state = 'IN', zip_code = '47243' WHERE name LIKE '%- 116' OR name LIKE '%- 116';
UPDATE locations SET location_code = '117', address = '1244 Vail Street', city = 'Princeton', state = 'IN', zip_code = '47670' WHERE name LIKE '%- 117' OR name LIKE '%- 117';
UPDATE locations SET location_code = '118', address = '2200 N. Riley Highway', city = 'Shelbyville', state = 'IN', zip_code = '46176' WHERE name LIKE '%- 118' OR name LIKE '%- 118';
UPDATE locations SET location_code = '119', address = '1014 Mill Pond Lane', city = 'Greencastle', state = 'IN', zip_code = '46135' WHERE name LIKE '%- 119' OR name LIKE '%- 119';
UPDATE locations SET location_code = '120', address = '1400 Lammers Pike', city = 'Batesville', state = 'IN', zip_code = '47006' WHERE name LIKE '%- 120' OR name LIKE '%- 120';
UPDATE locations SET location_code = '121', address = '966 N. Wilson Road', city = 'Scottsburg', state = 'IN', zip_code = '47170' WHERE name LIKE '%- 121' OR name LIKE '%- 121';
UPDATE locations SET location_code = '122', address = '303 N. Hurstbourne Pkwy.', city = 'Merrillville', state = 'IN', zip_code = '40222' WHERE name LIKE '%- 122' OR name LIKE '%- 122';
UPDATE locations SET location_code = '123', address = '2401 South L Street', city = 'Richmond FP', state = 'IN', zip_code = '47374' WHERE name LIKE '%- 123' OR name LIKE '%- 123';
UPDATE locations SET location_code = '124', address = '1332 Waterford Circle', city = 'Goshen MW', state = 'IN', zip_code = '46526' WHERE name LIKE '%- 124' OR name LIKE '%- 124';
UPDATE locations SET location_code = '125', address = '628 N. Meridian Road', city = 'Greenfield', state = 'IN', zip_code = '46140' WHERE name LIKE '%- 125' OR name LIKE '%- 125';
UPDATE locations SET location_code = '126', address = '6415 Calm River Way', city = 'Louisville GR', state = 'KY', zip_code = '40299' WHERE name LIKE '%- 126' OR name LIKE '%- 126';
UPDATE locations SET location_code = '127', address = '9700 Stonestreet Road', city = 'Louisville PT', state = 'KY', zip_code = '40272' WHERE name LIKE '%- 127' OR name LIKE '%- 127';
UPDATE locations SET location_code = '128', address = '4100 N Morrison Road', city = 'Muncie', state = 'IN', zip_code = '47304' WHERE name LIKE '%- 128' OR name LIKE '%- 128';
UPDATE locations SET location_code = '129', address = '1850 Howard Wayne Drive', city = 'Terre Haute CC', state = 'IN', zip_code = '47802' WHERE name LIKE '%- 129' OR name LIKE '%- 129';
UPDATE locations SET location_code = '130', address = '602 Woodbridge Avenue', city = 'Logansport', state = 'IN', zip_code = '46947' WHERE name LIKE '%- 130' OR name LIKE '%- 130';
UPDATE locations SET location_code = '131', address = '1900 College Avenue', city = 'Vincennes', state = 'IN', zip_code = '47591' WHERE name LIKE '%- 131' OR name LIKE '%- 131';
UPDATE locations SET location_code = '132', address = '1201 East Beardsley Avenue', city = 'Elkhart', state = 'IN', zip_code = '46514' WHERE name LIKE '%- 132' OR name LIKE '%- 132';
UPDATE locations SET location_code = '133', address = '1750 S Creasy Lane', city = 'Lafayette CS', state = 'IN', zip_code = '47905' WHERE name LIKE '%- 133' OR name LIKE '%- 133';
UPDATE locations SET location_code = '134', address = '701 Armory Road', city = 'Delphi', state = 'IN', zip_code = '46923' WHERE name LIKE '%- 134' OR name LIKE '%- 134';
UPDATE locations SET location_code = '135', address = '1051 Cumberland Avenue', city = 'West Lafayette', state = 'IN', zip_code = '47906' WHERE name LIKE '%- 135' OR name LIKE '%- 135';
UPDATE locations SET location_code = '136', address = '2201 Cason Street', city = 'Lafayette SM', state = 'IN', zip_code = '47904' WHERE name LIKE '%- 136' OR name LIKE '%- 136';
UPDATE locations SET location_code = '137', address = '3625 Fern Valley Road', city = 'Louisville FR', state = 'KY', zip_code = '40219' WHERE name LIKE '%- 137' OR name LIKE '%- 137';
UPDATE locations SET location_code = '139', address = '2400 Silhavy Road', city = 'Valparaiso', state = 'IN', zip_code = '46383' WHERE name LIKE '%- 139' OR name LIKE '%- 139';
UPDATE locations SET location_code = '140', address = '814 S. 6th Street', city = 'Monticello', state = 'IN', zip_code = '47960' WHERE name LIKE '%- 140' OR name LIKE '%- 140';
UPDATE locations SET location_code = '141', address = '9730 Prairie Lakes Blvd East', city = 'Noblesville', state = 'IN', zip_code = '46060' WHERE name LIKE '%- 141' OR name LIKE '%- 141';
UPDATE locations SET location_code = '142', address = '714 S. Eickhoff Road', city = 'Evansville WR', state = 'IN', zip_code = '47712' WHERE name LIKE '%- 142' OR name LIKE '%- 142';
UPDATE locations SET location_code = '143', address = '181 Campus Drive', city = 'Lawrenceburg', state = 'IN', zip_code = '47025' WHERE name LIKE '%- 143' OR name LIKE '%- 143';
UPDATE locations SET location_code = '144', address = '269 Meadowview Drive', city = 'Peru', state = 'IN', zip_code = '46970' WHERE name LIKE '%- 144' OR name LIKE '%- 144';
UPDATE locations SET location_code = '145', address = '4247 Westport Road', city = 'Louisville WP', state = 'KY', zip_code = '40207' WHERE name LIKE '%- 145' OR name LIKE '%- 145';
UPDATE locations SET location_code = '146', address = '2531 Old Rosebud Road', city = 'Lexington WH', state = 'KY', zip_code = '40509' WHERE name LIKE '%- 146' OR name LIKE '%- 146';
UPDATE locations SET location_code = '147', address = '2710 Man O War Blvd', city = 'Lexington WF', state = 'KY', zip_code = '40515' WHERE name LIKE '%- 147' OR name LIKE '%- 147';
UPDATE locations SET location_code = '148', address = '1376 Silver Springs Drive', city = 'Lexington WC', state = 'KY', zip_code = '40511' WHERE name LIKE '%- 148' OR name LIKE '%- 148';
UPDATE locations SET location_code = '149', address = '3043 North Lintel Drive', city = 'Bloomington HS', state = 'IN', zip_code = '47404' WHERE name LIKE '%- 149' OR name LIKE '%- 149';
UPDATE locations SET location_code = '150', address = '2320 N. Montgomery Road', city = 'Greensburg', state = 'IN', zip_code = '47240' WHERE name LIKE '%- 150' OR name LIKE '%- 150';
UPDATE locations SET location_code = '151', address = '1 Silvercrest Drive', city = 'New Albany SC', state = 'IN', zip_code = '47150' WHERE name LIKE '%- 151' OR name LIKE '%- 151';
UPDATE locations SET location_code = '152', address = '2800 Forest Ridge Parkway', city = 'New Castle SL', state = 'IN', zip_code = '47362' WHERE name LIKE '%- 152' OR name LIKE '%- 152';
UPDATE locations SET location_code = '153', address = '601 West C.R. 200 South', city = 'New Castle GO', state = 'IN', zip_code = '47362' WHERE name LIKE '%- 153' OR name LIKE '%- 153';
UPDATE locations SET location_code = '154', address = '4120 Wooded Acre Lane', city = 'Louisville FS', state = 'KY', zip_code = '40245' WHERE name LIKE '%- 154' OR name LIKE '%- 154';
UPDATE locations SET location_code = '156', address = '18275 Burr Street', city = 'Lowell', state = 'IN', zip_code = '46356' WHERE name LIKE '%- 156' OR name LIKE '%- 156';
UPDATE locations SET location_code = '157', address = '120 Presbyterian Avenue', city = 'Madison', state = 'IN', zip_code = '47250' WHERE name LIKE '%- 157' OR name LIKE '%- 157';
UPDATE locations SET location_code = '160', address = '1635 N. Arlington Avenue', city = 'Indianapolis AP', state = 'IN', zip_code = '46218' WHERE name LIKE '%- 160' OR name LIKE '%- 160';
UPDATE locations SET location_code = '161', address = '8405 Clearvista Place', city = 'Indianapolis CL', state = 'IN', zip_code = '46256' WHERE name LIKE '%- 161' OR name LIKE '%- 161';
UPDATE locations SET location_code = '162', address = '2402 South Street', city = 'Lafayette SL', state = 'IN', zip_code = '47904' WHERE name LIKE '%- 162' OR name LIKE '%- 162';
UPDATE locations SET location_code = '163', address = '395 8th Avenue', city = 'Terre Haute HC', state = 'IN', zip_code = '47804' WHERE name LIKE '%- 163' OR name LIKE '%- 163';
UPDATE locations SET location_code = '164', address = '363 S Fieldstone Blvd', city = 'Bloomington SC', state = 'IN', zip_code = '47403' WHERE name LIKE '%- 164' OR name LIKE '%- 164';
UPDATE locations SET location_code = '165', address = '12315 Pennsylvania St', city = 'Carmel', state = 'IN', zip_code = '46032' WHERE name LIKE '%- 165' OR name LIKE '%- 165';
UPDATE locations SET location_code = '166', address = '10307 E County Rd 100 North', city = 'Avon', state = 'IN', zip_code = '46234' WHERE name LIKE '%- 166' OR name LIKE '%- 166';
UPDATE locations SET location_code = '167', address = '517 Concord Drive', city = 'Crawfordsville', state = 'IN', zip_code = '47933' WHERE name LIKE '%- 167' OR name LIKE '%- 167';
UPDATE locations SET location_code = '168', address = '2200 S. Dixon Road', city = 'Kokomo WK', state = 'IN', zip_code = '46902' WHERE name LIKE '%- 168' OR name LIKE '%- 168';
UPDATE locations SET location_code = '169', address = '52565 Indiana 933', city = 'South Bend', state = 'IN', zip_code = '46637' WHERE name LIKE '%- 169' OR name LIKE '%- 169';
UPDATE locations SET location_code = '170', address = '20 John Kissinger Drive', city = 'Wabash', state = 'IN', zip_code = '46992' WHERE name LIKE '%- 170' OR name LIKE '%- 170';
UPDATE locations SET location_code = '171', address = '937 E 186th Street', city = 'Westfield', state = 'IN', zip_code = '46074' WHERE name LIKE '%- 171' OR name LIKE '%- 171';
UPDATE locations SET location_code = '173', address = '400 Industries Road', city = 'Richmond SR', state = 'IN', zip_code = '47374' WHERE name LIKE '%- 173' OR name LIKE '%- 173';
UPDATE locations SET location_code = '174', address = '302 North Johnson Rd', city = 'Mooresville', state = 'IN', zip_code = '46158' WHERE name LIKE '%- 174' OR name LIKE '%- 174';
UPDATE locations SET location_code = '175', address = '2200 Stony Brook Drive', city = 'Louisville SB', state = 'KY', zip_code = '40220' WHERE name LIKE '%- 175' OR name LIKE '%- 175';
UPDATE locations SET location_code = '176', address = '119 E Sanders Lane', city = 'Mt. Washington', state = 'KY', zip_code = '40047' WHERE name LIKE '%- 176' OR name LIKE '%- 176';
UPDATE locations SET location_code = '180', address = '871 Pacer Drive NW', city = 'Corydon', state = 'IN', zip_code = '47112' WHERE name LIKE '%- 180' OR name LIKE '%- 180';
UPDATE locations SET location_code = '184', address = '1212 Waterford Circle', city = 'Goshen RW', state = 'IN', zip_code = '46526' WHERE name LIKE '%- 184' OR name LIKE '%- 184';
UPDATE locations SET location_code = '185', address = '702 N Sawyer Road', city = 'Kendallville', state = 'IN', zip_code = '46755' WHERE name LIKE '%- 185' OR name LIKE '%- 185';
UPDATE locations SET location_code = '186', address = '811 East Baseline Road', city = 'Evansville NR', state = 'IN', zip_code = '47725' WHERE name LIKE '%- 186' OR name LIKE '%- 186';
UPDATE locations SET location_code = '187', address = '180 Lucky Man Way', city = 'Harrodsburg', state = 'KY', zip_code = '40330' WHERE name LIKE '%- 187' OR name LIKE '%- 187';
UPDATE locations SET location_code = '190', address = '3001 N Hurstbourne Pkwy', city = 'Louisville WS', state = 'KY', zip_code = '40241' WHERE name LIKE '%- 190' OR name LIKE '%- 190';
UPDATE locations SET location_code = '210', address = '13700 English Villa Drive', city = 'Louisville ES', state = 'KY', zip_code = '40245' WHERE name LIKE '%- 210' OR name LIKE '%- 210';
UPDATE locations SET location_code = '211', address = '7200 Heritage Springs Drive', city = 'West Chester', state = 'OH', zip_code = '45069' WHERE name LIKE '%- 211' OR name LIKE '%- 211';
UPDATE locations SET location_code = '221', address = '3001 N Hurstbourne Pkwy', city = 'Louisville SP', state = 'KY', zip_code = '40241' WHERE name LIKE '%- 221' OR name LIKE '%- 221';
UPDATE locations SET location_code = '231', address = '100 Davco Drive', city = 'Danville', state = 'KY', zip_code = '40422' WHERE name LIKE '%- 231' OR name LIKE '%- 231';
UPDATE locations SET location_code = '232', address = '2101 Old Boonesboro Road', city = 'Winchester', state = 'KY', zip_code = '40391' WHERE name LIKE '%- 232' OR name LIKE '%- 232';
UPDATE locations SET location_code = '233', address = '325 Lincoln Way', city = 'Bardstown', state = 'KY', zip_code = '40004' WHERE name LIKE '%- 233' OR name LIKE '%- 233';
UPDATE locations SET location_code = '234', address = '100 Williamsburg Drive', city = 'Shelbyville', state = 'KY', zip_code = '40065' WHERE name LIKE '%- 234' OR name LIKE '%- 234';
UPDATE locations SET location_code = '302', address = '2695 Shelden St', city = 'Warsaw', state = 'IN', zip_code = '46582' WHERE name LIKE '%- 302' OR name LIKE '%- 302';
UPDATE locations SET location_code = '303', address = '710 Sunrise Drive', city = 'Ferdinand', state = 'IN', zip_code = '47532' WHERE name LIKE '%- 303' OR name LIKE '%- 303';
UPDATE locations SET location_code = '304', address = '801 East Illinois Street', city = 'Petersburg', state = 'IN', zip_code = '47567' WHERE name LIKE '%- 304' OR name LIKE '%- 304';
UPDATE locations SET location_code = '305', address = '1694 Troy Road', city = 'Washington', state = 'IN', zip_code = '47501' WHERE name LIKE '%- 305' OR name LIKE '%- 305';
UPDATE locations SET location_code = '307', address = '710 Sunrise Drive', city = 'Ferdinand', state = 'IN', zip_code = '47532' WHERE name LIKE '%- 307' OR name LIKE '%- 307';
UPDATE locations SET location_code = '401', address = '2150 Montego Drive', city = 'Springfield FG', state = 'OH', zip_code = '45503' WHERE name LIKE '%- 401' OR name LIKE '%- 401';
UPDATE locations SET location_code = '403', address = '1247 N. River Road', city = 'Fremont', state = 'OH', zip_code = '43420' WHERE name LIKE '%- 403' OR name LIKE '%- 403';
UPDATE locations SET location_code = '406', address = '755 Ottawa Street', city = 'Kalida', state = 'OH', zip_code = '45853' WHERE name LIKE '%- 406' OR name LIKE '%- 406';
UPDATE locations SET location_code = '407', address = '800 Ambrose Drive', city = 'Delphos', state = 'OH', zip_code = '45833' WHERE name LIKE '%- 407' OR name LIKE '%- 407';
UPDATE locations SET location_code = '408', address = '2820 Greenacre Drive', city = 'Findlay', state = 'OH', zip_code = '45840' WHERE name LIKE '%- 408' OR name LIKE '%- 408';
UPDATE locations SET location_code = '409', address = '901 East Main Street', city = 'Leipsic', state = 'OH', zip_code = '45856' WHERE name LIKE '%- 409' OR name LIKE '%- 409';
UPDATE locations SET location_code = '410', address = '883 W. Spring Street', city = 'Lima', state = 'OH', zip_code = '45805' WHERE name LIKE '%- 410' OR name LIKE '%- 410';
UPDATE locations SET location_code = '411', address = '300 Cherry Street', city = 'Genoa', state = 'OH', zip_code = '43430' WHERE name LIKE '%- 411' OR name LIKE '%- 411';
UPDATE locations SET location_code = '412', address = '11230 Pippin Road', city = 'Colerain', state = 'OH', zip_code = '45231' WHERE name LIKE '%- 412' OR name LIKE '%- 412';
UPDATE locations SET location_code = '414', address = '101 Auxiliary Drive', city = 'Bellevue', state = 'OH', zip_code = '44811' WHERE name LIKE '%- 414' OR name LIKE '%- 414';
UPDATE locations SET location_code = '415', address = '600 Sterling Drive', city = 'North Baltimore', state = 'OH', zip_code = '45872' WHERE name LIKE '%- 415' OR name LIKE '%- 415';
UPDATE locations SET location_code = '416', address = '600 W. National Road', city = 'Englewood', state = 'OH', zip_code = '45322' WHERE name LIKE '%- 416' OR name LIKE '%- 416';
UPDATE locations SET location_code = '418', address = '4114 N. State Route 376 NW', city = 'McConnelsville', state = 'OH', zip_code = '43756' WHERE name LIKE '%- 418' OR name LIKE '%- 418';
UPDATE locations SET location_code = '419', address = '3291 Northpointe Drive', city = 'Zanesville ON', state = 'OH', zip_code = '43701' WHERE name LIKE '%- 419' OR name LIKE '%- 419';
UPDATE locations SET location_code = '421', address = '603 Diley Road', city = 'Pickerington', state = 'OH', zip_code = '43147' WHERE name LIKE '%- 421' OR name LIKE '%- 421';
UPDATE locations SET location_code = '422', address = '6935 Monclova Road', city = 'Monclova', state = 'OH', zip_code = '43537' WHERE name LIKE '%- 422' OR name LIKE '%- 422';
UPDATE locations SET location_code = '423', address = '1315 KitchenAid Way', city = 'Greenville', state = 'OH', zip_code = '45331' WHERE name LIKE '%- 423' OR name LIKE '%- 423';
UPDATE locations SET location_code = '424', address = '1050 Neal Zick Road', city = 'Willard', state = 'OH', zip_code = '44890' WHERE name LIKE '%- 424' OR name LIKE '%- 424';
UPDATE locations SET location_code = '425', address = '2971 Maple Avenue', city = 'Zanesville OB', state = 'OH', zip_code = '43701' WHERE name LIKE '%- 425' OR name LIKE '%- 425';
UPDATE locations SET location_code = '427', address = '5351 Mitchaw Road', city = 'Sylvania', state = 'OH', zip_code = '43560' WHERE name LIKE '%- 427' OR name LIKE '%- 427';
UPDATE locations SET location_code = '429', address = '2900 Bechtle Avenue', city = 'Springfield WG', state = 'OH', zip_code = '45504' WHERE name LIKE '%- 429' OR name LIKE '%- 429';
UPDATE locations SET location_code = '430', address = '147 Putnam Parkway', city = 'Ottawa', state = 'OH', zip_code = '45875' WHERE name LIKE '%- 430' OR name LIKE '%- 430';
UPDATE locations SET location_code = '432', address = '800 Ambrose Dr', city = 'Delphos', state = 'OH', zip_code = '45833' WHERE name LIKE '%- 432' OR name LIKE '%- 432';
UPDATE locations SET location_code = '433', address = '370 N Eastown Road', city = 'Lima SL', state = 'OH', zip_code = '45807' WHERE name LIKE '%- 433' OR name LIKE '%- 433';
UPDATE locations SET location_code = '434', address = '4300 Gleneste Withamsville Rd', city = 'Union Township', state = 'OH', zip_code = '45245' WHERE name LIKE '%- 434' OR name LIKE '%- 434';
UPDATE locations SET location_code = '435', address = '410 Fair Lane', city = 'Tiffin', state = 'OH', zip_code = '44883' WHERE name LIKE '%- 435' OR name LIKE '%- 435';
UPDATE locations SET location_code = '436', address = '748 Taylor Road', city = 'Gahanna', state = 'OH', zip_code = '43230' WHERE name LIKE '%- 436' OR name LIKE '%- 436';
UPDATE locations SET location_code = '437', address = '4549 Davidson Rd', city = 'Hilliard', state = 'OH', zip_code = '43026' WHERE name LIKE '%- 437' OR name LIKE '%- 437';
UPDATE locations SET location_code = '438', address = '7320 Smith''s Mill Rd', city = 'New Albany', state = 'OH', zip_code = '43054' WHERE name LIKE '%- 438' OR name LIKE '%- 438';
UPDATE locations SET location_code = '439', address = '7250 Gateway Ave', city = 'Hamilton', state = 'OH', zip_code = '45011' WHERE name LIKE '%- 439' OR name LIKE '%- 439';
UPDATE locations SET location_code = '440', address = '2510 Vienna Pkwy', city = 'Miamisburg', state = 'OH', zip_code = '45449' WHERE name LIKE '%- 440' OR name LIKE '%- 440';
UPDATE locations SET location_code = '442', address = '10460 Progress Way', city = 'Harrison', state = 'OH', zip_code = '45030' WHERE name LIKE '%- 442' OR name LIKE '%- 442';
UPDATE locations SET location_code = '501', address = '706 North Avenue', city = 'Battle Creek', state = 'MI', zip_code = '49017' WHERE name LIKE '%- 501' OR name LIKE '%- 501';
UPDATE locations SET location_code = '502', address = '703 Robinson Road', city = 'Jackson', state = 'MI', zip_code = '49203' WHERE name LIKE '%- 502' OR name LIKE '%- 502';
UPDATE locations SET location_code = '503', address = '10735 Bogie Lake Road', city = 'Commerce', state = 'MI', zip_code = '48382' WHERE name LIKE '%- 503' OR name LIKE '%- 503';
UPDATE locations SET location_code = '504', address = '4830 Central Park Drive', city = 'Okemos', state = 'MI', zip_code = '48864' WHERE name LIKE '%- 504' OR name LIKE '%- 504';
UPDATE locations SET location_code = '505', address = '5370 E. Baldwin Road', city = 'Grand Blanc', state = 'MI', zip_code = '48439' WHERE name LIKE '%- 505' OR name LIKE '%- 505';
UPDATE locations SET location_code = '506', address = '2525 DeMille Blvd.', city = 'Lapeer', state = 'MI', zip_code = '48446' WHERE name LIKE '%- 506' OR name LIKE '%- 506';
UPDATE locations SET location_code = '507', address = '3500 Coolidge Road', city = 'East Lansing', state = 'MI', zip_code = '48823' WHERE name LIKE '%- 507' OR name LIKE '%- 507';
UPDATE locations SET location_code = '508', address = '13794 21 Mile Road', city = 'Macomb', state = 'MI', zip_code = '48315' WHERE name LIKE '%- 508' OR name LIKE '%- 508';
UPDATE locations SET location_code = '509', address = '1500 Byron Road', city = 'Howell', state = 'MI', zip_code = '48855' WHERE name LIKE '%- 509' OR name LIKE '%- 509';
UPDATE locations SET location_code = '510', address = '41795 Twelve Mile Road', city = 'Novi', state = 'MI', zip_code = '48377' WHERE name LIKE '%- 510' OR name LIKE '%- 510';
UPDATE locations SET location_code = '512', address = '71150 Orchard Crossing Lane', city = 'Romeo', state = 'MI', zip_code = '48065' WHERE name LIKE '%- 512' OR name LIKE '%- 512';
UPDATE locations SET location_code = '518', address = '2280 Byron View Drive SW', city = 'Byron Center', state = 'MI', zip_code = '49315' WHERE name LIKE '%- 518' OR name LIKE '%- 518';
UPDATE locations SET location_code = '519', address = '6081 West River Drive NE', city = 'Belmont', state = 'MI', zip_code = '49306' WHERE name LIKE '%- 519' OR name LIKE '%- 519';
UPDATE locations SET location_code = '611', address = '1635 N Arlington Avenue', city = 'Indianapolis', state = 'IN', zip_code = '46218' WHERE name LIKE '%- 611' OR name LIKE '%- 611';
UPDATE locations SET location_code = '630', address = '800 St Joseph Drive', city = 'Kokomo', state = 'IN', zip_code = '46901' WHERE name LIKE '%- 630' OR name LIKE '%- 630';
UPDATE locations SET location_code = '631', address = '3625 Fern Valley Road', city = 'Louisville', state = 'KY', zip_code = '40219' WHERE name LIKE '%- 631' OR name LIKE '%- 631';
UPDATE locations SET location_code = '632', address = '11230 Pippin Road', city = 'Cincinnati', state = 'OH', zip_code = '45231' WHERE name LIKE '%- 632' OR name LIKE '%- 632';