/**
 * In-House Rate Planning — shared vocabulary.
 *
 * These types cross the server/client boundary, so they describe the *result*
 * of the planning calculation rather than any of the machinery that produces
 * it. The solver itself lives in server/services/inhouseRatePlanning.
 *
 * ── One rate space ─────────────────────────────────────────────────────────
 * Every `...Monthly` field is a NORMALIZED MONTHLY rate. HC and HC/MC are
 * stored as daily rates in the rent roll, and mixing the two bases makes the
 * arithmetic wrong by roughly 30x. Conversion happens once on the way in and
 * once on the way out; the `...Display` fields carry the value in whatever
 * unit that service line is actually billed in, together with `rateBasis` so
 * the UI can label it.
 */

export type EqualizationStrength = "low" | "medium" | "high";

export type MeasurementMode = "quarterly_yoy";

/** Basis on which a quarter's realized rate was established. */
export type QuarterBasis =
  /** Every month of the quarter is present in the rent roll. */
  | "actual"
  /** Some months present, some missing — a real number over a short window. */
  | "partial"
  /** No data at all; extrapolated from trend. Never present this as fact. */
  | "projected";

/** Why a resident's increase landed where it did. */
export type ResidentConstraint =
  /** Free — the allocation formula chose this value outright. */
  | "none"
  /** Pinned up to the configured minimum increase. */
  | "min"
  /** Pinned down to the configured maximum increase. */
  | "max"
  /** Held below the maximum because the new rate would have passed street. */
  | "street_cap"
  /** Already at or above street with no headroom at all, so no increase. */
  | "at_or_above_street";

/**
 * An operator-readable derivation. Generated by the calculation layer itself
 * so the words cannot drift away from the arithmetic they describe.
 */
export interface CalcExplanation {
  headline: string;
  steps: Array<{ label: string; value: string; note?: string }>;
  narrative: string[];
}

export interface PlanningAssumptions {
  /** Annual YoY realized-rate growth objective, in percent (5 = 5%). */
  rateGrowthTargetPct: number;
  measurementMode: MeasurementMode;
  /** ISO date the recommended street rate starts applying to move-ins. */
  streetRateEffectiveDate: string;
  /** ISO date the in-house increases hit existing residents' bills. */
  inhouseEffectiveDate: string;
  /** Expected annual resident turnover, in percent (35 = 35%). */
  annualTurnoverPct: number;
  /** Floor on any single resident's increase, in percent. */
  minInhouseIncreasePct: number;
  /** Ceiling on any single resident's increase, in percent. */
  maxInhouseIncreasePct: number;
  /** How widely resident increases spread around the required average. */
  equalizationStrength: EqualizationStrength;
  /** When false, a resident's new rate may never exceed their street rate. */
  allowInhouseAboveStreet: boolean;
  /**
   * Ceiling on how far the solver may push the street rate while looking for
   * a feasible plan, in percent. Raising street rate is the only lever that
   * creates in-house headroom, so this is the outer bound of the search.
   */
  maxStreetIncreasePct: number;
}

export const DEFAULT_ASSUMPTIONS: PlanningAssumptions = {
  rateGrowthTargetPct: 6,
  measurementMode: "quarterly_yoy",
  streetRateEffectiveDate: "",
  inhouseEffectiveDate: "",
  annualTurnoverPct: 35,
  minInhouseIncreasePct: 0,
  maxInhouseIncreasePct: 8,
  equalizationStrength: "medium",
  allowInhouseAboveStreet: false,
  maxStreetIncreasePct: 15,
};

/** A resident as the solver sees them. */
export interface PlanningResident {
  /**
   * Stable composite identity. The rent roll carries no resident id at all
   * (100% NULL across every row), so a resident is campus + service line +
   * room + move-in date. Two people can hold the same room over time; the
   * move-in date is what separates them.
   */
  key: string;
  location: string;
  serviceLine: string;
  roomNumber: string;
  roomType: string | null;
  careLevel: string | null;
  payorType: string | null;
  /** ISO date, or null when the source row had no move-in date. */
  moveInDate: string | null;
  currentRateMonthly: number;
  streetRateMonthly: number;
  /**
   * Companion ("B bed") rows are excluded from street-rate AVERAGES but they
   * are real people with real in-house rates, so they still receive
   * increases. Flagged only so the UI can label them.
   */
  isCompanionBed: boolean;
  /**
   * Resident-day weight over the measurement window. Derived from the stay's
   * overlap with the period where move-in/out dates allow, otherwise the
   * count of occupied monthly snapshots.
   */
  weight: number;
}

export interface QuarterRef {
  year: number;
  quarter: number;
  /** "Q1 2027" */
  label: string;
}

export interface BaselineQuarter extends QuarterRef {
  realizedRateMonthly: number | null;
  basis: QuarterBasis;
  monthsAvailable: number;
  monthsExpected: number;
  residentDays: number;
}

export interface QuarterResult extends QuarterRef {
  priorYear: BaselineQuarter;
  requiredRateMonthly: number;
  projectedRateMonthly: number;
  /** Projected vs prior-year, in percent. */
  yoyGrowthPct: number;
  passes: boolean;
  /** Percentage points short of the target. Negative when passing. */
  shortfallPct: number;
  isBinding: boolean;
  explanation: CalcExplanation;
}

export interface ResidentRecommendation {
  key: string;
  location: string;
  roomNumber: string;
  roomType: string | null;
  careLevel: string | null;
  moveInDate: string | null;
  isCompanionBed: boolean;
  currentRateMonthly: number;
  streetRateMonthly: number;
  gapToStreetPct: number;
  gapToStreetDollarsMonthly: number;
  increasePct: number;
  increaseDollarsMonthly: number;
  newRateMonthly: number;
  newGapToStreetPct: number;
  constraint: ResidentConstraint;
  /** Same numbers in the unit this service line is billed in. */
  rateBasis: "monthly" | "daily";
  currentRateDisplay: number;
  newRateDisplay: number;
  increaseDollarsDisplay: number;
  explanation: CalcExplanation;
}

export type BindingConstraint =
  | "max_increase"
  | "street_cap"
  | "street_ceiling"
  | "no_headroom";

export interface Infeasibility {
  bindingConstraint: BindingConstraint;
  /** Plain-language statement of what stops the target being reached. */
  message: string;
  /** Quarter that fails by the widest margin. */
  bindingQuarterLabel: string | null;
  /** Weighted-average increase the target actually needs, in percent. */
  requiredAvgIncreasePct: number;
  /** The best weighted-average increase the constraints permit, in percent. */
  achievableAvgIncreasePct: number;
  /** Smallest single change that would make the target reachable. */
  minimumChange: {
    /** Maximum-increase setting that would suffice, in percent. Null if none would. */
    maxInhouseIncreasePct: number | null;
    /** Street increase that would suffice, in percent. Null if none would. */
    streetIncreasePct: number | null;
    /** Growth target that IS reachable as configured, in percent. */
    achievableGrowthTargetPct: number;
  };
}

export interface PlanScope {
  clientId: string;
  locationId: string | null;
  location: string | null;
  serviceLine: string;
  /** Latest rent-roll month the resident population was read from. */
  sourceMonth: string;
}

export interface PlanSummary {
  residentCount: number;
  residentsReceivingIncrease: number;
  residentsAtMin: number;
  residentsAtMax: number;
  residentsBlockedByStreet: number;
  weightedAvgIncreasePct: number;
  minIncreasePct: number;
  maxIncreasePct: number;
  totalMonthlyIncreaseDollars: number;
  totalAnnualIncreaseDollars: number;
  currentAvgInhouseRateMonthly: number;
  newAvgInhouseRateMonthly: number;
}

export interface PlanResult {
  scope: PlanScope;
  assumptions: PlanningAssumptions;
  feasible: boolean;
  rateBasis: "monthly" | "daily";

  currentStreetRateMonthly: number;
  recommendedStreetRateMonthly: number;
  streetIncreasePct: number;
  streetIncreaseDollarsMonthly: number;
  currentStreetRateDisplay: number;
  recommendedStreetRateDisplay: number;

  requiredWeightedAvgIncreasePct: number;

  quarters: QuarterResult[];
  bindingQuarterLabel: string | null;

  summary: PlanSummary;
  residents: ResidentRecommendation[];

  infeasibility: Infeasibility | null;
  explanation: CalcExplanation;
  /** Data-quality caveats an operator needs to see, in plain language. */
  warnings: string[];
}

/** Quarter label used everywhere: "Q3 2026". */
export function quarterLabel(year: number, quarter: number): string {
  return `Q${quarter} ${year}`;
}

export function formatPct(value: number, digits = 1): string {
  return `${value >= 0 ? "" : "-"}${Math.abs(value).toFixed(digits)}%`;
}

export function formatMoney(value: number, digits = 0): string {
  return `$${value.toLocaleString("en-US", {
    minimumFractionDigits: digits,
    maximumFractionDigits: digits,
  })}`;
}
