/**
 * In-House Rate Planning — shared vocabulary.
 *
 * These types cross the server/client boundary, so they describe the *result*
 * of the planning calculation rather than any of the machinery that produces
 * it. The solver itself lives in server/services/inhouseRatePlanning.
 *
 * ── One rate space ─────────────────────────────────────────────────────────
 * Every `...Monthly` field is a NORMALIZED MONTHLY rate. HC and HC/MC are
 * stored as daily rates in the rent roll, and mixing the two bases makes the
 * arithmetic wrong by roughly 30x. Conversion happens once on the way in and
 * once on the way out; the `...Display` fields carry the value in whatever
 * unit that service line is actually billed in, together with `rateBasis` so
 * the UI can label it.
 */

import type { RateProduct } from "./rateProduct";

export type { RateProduct };

export type EqualizationStrength = "low" | "medium" | "high";

export type MeasurementMode = "quarterly_yoy";

/** Historical Street Rate evidence retained only for reading old plan snapshots. */
export type StreetRecommendationAction = "push" | "measured_increase" | "hold";
/** Basis on which a quarter's realized rate was established. */
export type QuarterBasis =
  /** Every month of the quarter is present in the rent roll. */
  | "actual"
  /** Some months present, some missing — a real number over a short window. */
  | "partial"
  /**
   * Measured, but on rooms too few to meet the matching standard.
   *
   * Reached only when a scope is small enough that every stratum failed its
   * gate. The alternative is refusing to plan the scope at all, which helps
   * nobody, so the number is shown and labelled rather than dressed as an
   * actual.
   */
  | "ungated_fallback"
  /** No data at all; extrapolated from trend. Never present this as fact. */
  | "projected";

/** Why a resident's increase landed where it did. */
export type ResidentConstraint =
  /** Free — the allocation formula chose this value outright. */
  | "none"
  /** Pinned up to the configured minimum increase. */
  | "min"
  /** Pinned down to the configured maximum increase. */
  | "max"
  /** Held below the maximum because the new rate would have passed street. */
  | "street_cap"
  /** Already at or above street with no headroom at all, so no increase. */
  | "at_or_above_street";

/**
 * An operator-readable derivation. Generated by the calculation layer itself
 * so the words cannot drift away from the arithmetic they describe.
 */
export interface CalcExplanation {
  headline: string;
  steps: Array<{ label: string; value: string; note?: string }>;
  narrative: string[];
}

export interface PlanningAssumptions {
  /** Annual YoY realized-rate growth objective, in percent (5 = 5%). */
  rateGrowthTargetPct: number;
  measurementMode: MeasurementMode;
  /** ISO date the recommended street rate starts applying to move-ins. */
  streetRateEffectiveDate: string;
  /** ISO date the in-house increases hit existing residents' bills. */
  inhouseEffectiveDate: string;
  /** Expected annual resident turnover, in percent (35 = 35%). */
  annualTurnoverPct: number;
  /** Floor on any single resident's increase, in percent. */
  minInhouseIncreasePct: number;
  /** Ceiling on any single resident's increase, in percent. */
  maxInhouseIncreasePct: number;
  /** How widely resident increases spread around the required average. */
  equalizationStrength: EqualizationStrength;
  /** Legacy compatibility field. In-house rates are allowed above street. */
  allowInhouseAboveStreet: boolean;
  /**
   * Ceiling on how far the solver may push the street rate while looking for
   * a feasible plan, in percent. Raising street rate is the only lever that
   * creates in-house headroom, so this is the outer bound of the search.
   */
  maxStreetIncreasePct: number;
  /**
   * Minimum increase the combined plan should apply to Street Rate, subject to
   * the hard annual and January-to-January guardrails.
   */
  minStreetIncreasePct: number;
  /**
   * Desired position versus the authoritative Top Competitor, in percent.
   * This is a directional target, not a cap: being further below it pushes the
   * Street Rate recommendation higher, while hard guardrails remain separate.
   */
  desiredVarianceToTopCompetitorPct: number;
  /**
   * Maximum increase from the prior January rate to the proposed January rate,
   * in percent. This catches street increases already taken during the year
   * instead of treating today's rate as a fresh baseline.
   */
  maxYoYStreetIncreasePct: number;
}

export const DEFAULT_ASSUMPTIONS: PlanningAssumptions = {
  rateGrowthTargetPct: 6,
  measurementMode: "quarterly_yoy",
  streetRateEffectiveDate: "",
  inhouseEffectiveDate: "",
  annualTurnoverPct: 35,
  minInhouseIncreasePct: 0,
  maxInhouseIncreasePct: 8,
  equalizationStrength: "medium",
  allowInhouseAboveStreet: true,
  maxStreetIncreasePct: 15,
  minStreetIncreasePct: 0,
  desiredVarianceToTopCompetitorPct: 0,
  maxYoYStreetIncreasePct: 15,
};

/**
 * Where a resident's comparison street rate came from.
 *
 *   unit                 — the asking rate on that resident's own rent-roll row.
 *   product_median       — the median asking rate for the same product (second
 *                          occupant, semi-private, respite, rehab/TCU, or
 *                          single occupant) AT THAT CAMPUS, used when the row's
 *                          own rate is missing or implausible for its product.
 *   service_line_median  — the same median taken across the whole service line,
 *                          used when the campus prices no such product. Kept
 *                          distinct from the campus median because a reviewer
 *                          auditing a ceiling needs to know it came from other
 *                          buildings, not this one.
 *   derived_formula      — the configured derived-rate formula applied to the
 *                          base rate, used when the product is not priced on
 *                          any row anywhere to measure.
 *   none                 — no usable rate; the resident is planned with no
 *                          ceiling, limited only by the configured maximum
 *                          increase.
 */
export type StreetRateSource =
  | "unit"
  | "product_median"
  | "service_line_median"
  | "derived_formula"
  | "none";

/** A resident as the solver sees them. */
export interface PlanningResident {
  /**
   * Stable composite identity. The rent roll carries no resident id at all
   * (100% NULL across every row), so a resident is campus + service line +
   * room + move-in date. Two people can hold the same room over time; the
   * move-in date is what separates them.
   */
  key: string;
  location: string;
  serviceLine: string;
  roomNumber: string;
  roomType: string | null;
  careLevel: string | null;
  payorType: string | null;
  /** ISO date, or null when the source row had no move-in date. */
  moveInDate: string | null;
  currentRateMonthly: number;
  /**
   * The street rate this resident is measured against, for the PRODUCT they
   * occupy — a second-occupant rate for a companion bed, a semi-private rate
   * for a shared health-care bed, and so on. Never the single-occupancy base
   * rate unless the resident is in fact a single occupant.
   */
  streetRateMonthly: number;
  /** Which product the resident's rate prices. */
  rateProduct: RateProduct;
  /** Where `streetRateMonthly` came from. */
  streetRateSource: StreetRateSource;
  /**
   * Companion ("B bed") rows are excluded from street-rate AVERAGES but they
   * are real people with real in-house rates, so they still receive
   * increases. Flagged only so the UI can label them.
   */
  isCompanionBed: boolean;
  /**
   * Resident-day weight over the measurement window. Derived from the stay's
   * overlap with the period where move-in/out dates allow, otherwise the
   * count of occupied monthly snapshots.
   */
  weight: number;
}

export interface QuarterRef {
  year: number;
  quarter: number;
  /** "Q1 2027" */
  label: string;
}

export interface BaselineQuarter extends QuarterRef {
  realizedRateMonthly: number | null;
  basis: QuarterBasis;
  monthsAvailable: number;
  monthsExpected: number;
  /** Canonical YYYY-MM months that contributed qualifying planning rows. */
  availableMonths?: string[];
  residentDays: number;
}

export interface QuarterResult extends QuarterRef {
  priorYear: BaselineQuarter;
  requiredRateMonthly: number;
  projectedRateMonthly: number;
  /** Projected vs prior-year, in percent. */
  yoyGrowthPct: number;
  passes: boolean;
  /** Percentage points short of the target. Negative when passing. */
  shortfallPct: number;
  isBinding: boolean;
  explanation: CalcExplanation;
  /** Room-level bridge from today's occupant rate to this quarter's projection. */
  roomDetails?: QuarterRoomProjection[];
  /** Weighted average of roomDetails; should equal projectedRateMonthly. */
  roomDetailProjectedRateMonthly?: number;
  roomDetailTotals?: {
    currentRateMonthly: number;
    existingRateUsedMonthly: number;
    existingSharePct: number;
    replacementSharePct: number;
    replacementRateMonthly: number;
    projectedRateMonthly: number;
    changeMonthly: number;
  };
}

export interface MonthlyRateProjection {
  /** Canonical YYYY-MM month in the planning horizon. */
  month: string;
  /** Weighted projected realized rate for this month, normalized monthly. */
  projectedRateMonthly: number;
  /** Street Rate in force at month end, normalized monthly. */
  streetRateMonthly: number;
  /** Change from today's weighted-average in-house rate. */
  growthFromCurrentPct: number;
}

export interface QuarterRoomProjection {
  key: string;
  location: string;
  roomNumber: string;
  roomType: string | null;
  moveInDate: string | null;
  /** Rate paid by today's occupant before the plan. */
  currentRateMonthly: number;
  /** Rate for today's occupant after their planned increase is effective. */
  plannedExistingRateMonthly: number;
  /** Existing-occupant rate actually active on average during this quarter. */
  existingRateUsedMonthly: number;
  /** Expected share of the quarter still occupied by today's cohort. */
  existingSharePct: number;
  /** Expected share occupied by future move-ins under the turnover assumption. */
  replacementSharePct: number;
  /** Average move-in rate used for the replacement share in this quarter. */
  replacementRateMonthly: number;
  /** Blended existing + replacement rate for this room. */
  projectedRateMonthly: number;
  changeMonthly: number;
}

export interface ResidentRecommendation {
  key: string;
  location: string;
  roomNumber: string;
  roomType: string | null;
  careLevel: string | null;
  moveInDate: string | null;
  isCompanionBed: boolean;
  /** Which product this resident's rate prices — see `PlanningResident`. */
  rateProduct: RateProduct;
  /** Where the comparison street rate came from. */
  streetRateSource: StreetRateSource;
  currentRateMonthly: number;
  streetRateMonthly: number;
  gapToStreetPct: number;
  gapToStreetDollarsMonthly: number;
  increasePct: number;
  increaseDollarsMonthly: number;
  newRateMonthly: number;
  newGapToStreetPct: number;
  constraint: ResidentConstraint;
  /** Same numbers in the unit this service line is billed in. */
  rateBasis: "monthly" | "daily";
  currentRateDisplay: number;
  newRateDisplay: number;
  increaseDollarsDisplay: number;
  explanation: CalcExplanation;
}

export type BindingConstraint =
  | "max_increase"
  | "street_cap"
  | "street_ceiling"
  | "no_headroom";

export interface Infeasibility {
  bindingConstraint: BindingConstraint;
  /** Plain-language statement of what stops the target being reached. */
  message: string;
  /** Quarter that fails by the widest margin. */
  bindingQuarterLabel: string | null;
  /** Weighted-average increase the target actually needs, in percent. */
  requiredAvgIncreasePct: number;
  /** The best weighted-average increase the constraints permit, in percent. */
  achievableAvgIncreasePct: number;
  /** Smallest single change that would make the target reachable. */
  minimumChange: {
    /** Maximum-increase setting that would suffice, in percent. Null if none would. */
    maxInhouseIncreasePct: number | null;
    /** Street increase that would suffice, in percent. Null if none would. */
    streetIncreasePct: number | null;
    /** Growth target that IS reachable as configured, in percent. */
    achievableGrowthTargetPct: number;
  };
}

export interface PlanScope {
  clientId: string;
  locationId: string | null;
  location: string | null;
  serviceLine: string;
  /** Latest rent-roll month the resident population was read from. */
  sourceMonth: string;
}

export interface PlanSummary {
  residentCount: number;
  residentsReceivingIncrease: number;
  residentsAtMin: number;
  residentsAtMax: number;
  residentsBlockedByStreet: number;
  weightedAvgIncreasePct: number;
  minIncreasePct: number;
  maxIncreasePct: number;
  totalMonthlyIncreaseDollars: number;
  totalAnnualIncreaseDollars: number;
  currentAvgInhouseRateMonthly: number;
  newAvgInhouseRateMonthly: number;
  /** Legacy advisory Street Rate evidence, retained when reading old plans. */
  streetRateRecommendations?: StreetRateRecommendation[];
  streetRateRecommendationSnapshot?: StreetRateRecommendationSnapshot;
}

export interface StreetRateRecommendationSnapshot {
  createdAt: string;
  maximumPremiumAboveTopCompetitorPct: number | null;
  assumptionsFingerprint: string | null;
  recommendations: StreetRateRecommendation[];
}
export interface InhousePlanHistoryEntry {
  id: string;
  version: number;
  status: string;
  location: string | null;
  locationId: string | null;
  serviceLine: string;
  summary: PlanSummary;
  assumptions: PlanningAssumptions;
  recommendedStreetRate: number | null;
  inhouseEffectiveDate: string | null;
  appliedBy: string | null;
  createdAt: string | null;
}

export interface PlanResult {
  scope: PlanScope;
  assumptions: PlanningAssumptions;
  feasible: boolean;
  rateBasis: "monthly" | "daily";

  currentStreetRateMonthly: number;
  recommendedStreetRateMonthly: number;
  streetIncreasePct: number;
  streetIncreaseDollarsMonthly: number;
  currentStreetRateDisplay: number;
  recommendedStreetRateDisplay: number;
  /** Product-matched, care-adjusted Top Competitor benchmark, normalized monthly. */
  adjustedTopCompetitorRateMonthly?: number | null;

  requiredWeightedAvgIncreasePct: number;

  quarters: QuarterResult[];
  /** Exact monthly view of the same daily turnover/effective-date simulation. */
  monthlyRateProjection?: MonthlyRateProjection[];
  bindingQuarterLabel: string | null;

  summary: PlanSummary;
  residents: ResidentRecommendation[];

  infeasibility: Infeasibility | null;
  explanation: CalcExplanation;
  /** Data-quality caveats an operator needs to see, in plain language. */
  warnings: string[];
  /** How the historical series was standardized, and what it decomposes into. */
  standardization?: StandardizationDiagnostics;
}

/**
 * One quarter-to-quarter matched comparison, decomposed.
 *
 * Mix is reported, never suppressed. A portfolio whose realized rate rose
 * because expensive rooms filled and cheap ones emptied really did earn more;
 * that is a genuine economic outcome and an operator needs to see it. What it
 * is not is evidence that anyone raised a price, so it is reported beside the
 * rate effect rather than folded into it.
 */
export interface RateMixComparison {
  /** The historical quarter. */
  baseQuarterLabel: string;
  /** The quarter it is measured against — the latest complete one. */
  endingQuarterLabel: string;
  /** Unrestricted change, every qualifying row, no room matching. */
  rawChangePct: number | null;
  /** Stratified matched-room price movement, on ending-quarter weights. */
  rateEffectPct: number | null;
  /** Raw minus rate: what composition contributed. */
  mixEffectPct: number | null;
  /** Same stratum ratios re-aggregated on base-quarter weights. */
  baseWeightedRateEffectPct: number | null;
  /** Spread between the two weightings. */
  compositionEffectPct: number | null;
  matchedRooms: number;
  endingRooms: number;
  /** Matched rooms over rooms priced in the ending quarter. */
  coverageByCountPct: number;
  /** The same share measured in ending-quarter revenue. */
  coverageByRevenuePct: number;
  suppressedStrata: Array<{ key: string; reasonCode: string }>;
  usable: boolean;
  reasonCode: string | null;
}

/** Per-stratum detail for the headline year-over-year comparison. */
export interface RateMixStratum {
  key: string;
  unitType: string;
  careLevel: string;
  priceBand: number;
  matchedRooms: number;
  endingRooms: number;
  coverageByCountPct: number;
  coverageByRevenuePct: number;
  rateEffectPct: number | null;
  endingWeightSharePct: number;
  baseWeightSharePct: number;
  suppressed: boolean;
  reasonCode: string | null;
}

export interface StandardizationDiagnostics {
  method: "two_point_matched_quarter";
  /** The quarter every historical quarter is compared against. */
  endingQuarterLabel: string;
  /** Matched rooms a stratum needs before its ratio is believed. */
  minMatchedRooms: number;
  /** Coverage floor, applied only to strata large enough to have one. */
  coverageFloorPct: number;
  /** One entry per prior-year quarter, plus the strict four-quarter pair. */
  comparisons: RateMixComparison[];
  /** The strict year-over-year pair: latest complete quarter vs four back. */
  yearOverYear: RateMixComparison | null;
  /** Stratum detail for the year-over-year pair. */
  yearOverYearStrata: RateMixStratum[];
  /** Quarters withheld because no stratum in them could be believed. */
  suppressedQuarters: Array<{ label: string; reasonCode: string }>;
  /**
   * Parallel run. The previous balanced-panel baselines beside the matched-pair
   * ones; the gap between them is the entry/exit effect, and it needs to be
   * inspectable before the old series is retired.
   */
  parallelRun: Array<{
    label: string;
    matchedPairRateMonthly: number | null;
    balancedPanelRateMonthly: number | null;
    differencePct: number | null;
  }>;
}

/**
 * The fields that make a calculated plan safe to submit. Keep this list
 * aligned with the inputs sent to the calculator; legacy compatibility fields
 * that do not change the solver result intentionally stay out.
 */
export const SUBMISSION_ASSUMPTION_KEYS: Array<keyof PlanningAssumptions> = [
  "rateGrowthTargetPct",
  "measurementMode",
  "streetRateEffectiveDate",
  "inhouseEffectiveDate",
  "annualTurnoverPct",
  "minInhouseIncreasePct",
  "maxInhouseIncreasePct",
  "equalizationStrength",
  "maxStreetIncreasePct",
  "minStreetIncreasePct",
  "desiredVarianceToTopCompetitorPct",
  "maxYoYStreetIncreasePct",
];

export function planAssumptionsMatch(
  calculated: PlanningAssumptions,
  current: PlanningAssumptions,
): boolean {
  return SUBMISSION_ASSUMPTION_KEYS.every((key) => calculated[key] === current[key]);
}

export interface PlanSubmissionCandidate {
  sl: string;
  plan: Pick<PlanResult, "feasible" | "assumptions">;
}

/**
 * A multi-line calculation can contain both valid and infeasible results.
 * Only feasible lines may be sent to the apply endpoint.
 */
export function selectSubmittablePlans<T extends PlanSubmissionCandidate>(plans: T[]): T[] {
  return plans.filter(({ plan }) => plan.feasible);
}

/** Quarter label used everywhere: "Q3 2026". */
export function quarterLabel(year: number, quarter: number): string {
  return `Q${quarter} ${year}`;
}

export function formatPct(value: number, digits = 1): string {
  return `${value >= 0 ? "" : "-"}${Math.abs(value).toFixed(digits)}%`;
}

export function formatMoney(value: number, digits = 0): string {
  return `$${value.toLocaleString("en-US", {
    minimumFractionDigits: digits,
    maximumFractionDigits: digits,
  })}`;
}

export interface StreetRateRecommendation {
  id: string;
  location: string;
  benchmarkLocation?: string;
  locationId: string | null;
  serviceLine: string;
  product: string;
  currentStreetRate: number;
  topCompetitorRate: number | null;
  premiumCeilingRate: number | null;
  hardCeiling: number;
  suggestedRate: number;
  suggestedIncreasePct: number;
  action: StreetRecommendationAction;
  rationale: string;
  units: number;
  occupancyPct: number | null;
  locked: boolean;
  growthContribution: number;
  validation: string[];
}
